### ISSUE TITLE
After saving an event the title dissappear

### ISSUE THREAD

**Issue by mikemastercorp** [HadiNiazi/fullCalendar-js-in-Laravel#2]
After installing successfully the Laravel profile and adding a few events, the board shows all the events correctly, however after a page refresh. the title of the event disappear and it only shows the time when it was added. If I grab such event and drag it to another date, the title reappear. Seems like in the DB the events are saved correctly and after a drag to another date they show correctly so something must be incorrect in the index view of the initial load or after a page refresh.

# Events after initial adding
![EVENTS-VIEW-AFTER-ADDING](https://user-images.githubusercontent.com/33164955/181313641-e1e0850a-4a62-41e5-8cb8-3e0e4520f5f5.png)

# Events after a page refresh
![EVENTS-VIEW-AFTER-REFRESH](https://user-images.githubusercontent.com/33164955/181313639-c4d66aec-0a9e-41af-9a29-1e140b21f02b.png)

# Events after a drag&drop of a single event to another date
![EVENTS-VIEW-AFTER-DRAG](https://user-images.githubusercontent.com/33164955/181313638-44442de8-0ad1-4b3f-a4fb-f5ff9bca9183.png)

.

**Comment by mikemastercorp** [comment]
Sorry, my mistake. I've missed the fact that you had some custom styling which changed the width of every event to 20px. Removing that one resolved the issue.

**Comment by HadiNiazi** [comment]
@mikemastercorp are you sure you are passing the title key to fullCalendar js.

**Comment by HadiNiazi** [comment]
@mikemastercorp is getting this due to a styling issue. There is no issue in the code
