### ISSUE TITLE
The Booking Title is getting hide when the page refreshes.

### ISSUE THREAD

**Issue by sayedahmadnawid** [HadiNiazi/fullCalendar-js-in-Laravel#3]
Why does the booking go hide after the pages refreshes? The Ajax call is not run I guess.  

<img width="1263" alt="Screen Shot 2023-06-15 at 16 10 26" src="https://github.com/HadiNiazi/fullCalendar-js-in-Laravel/assets/12025673/de972c99-aae5-4325-9638-8f1a56f7253a">

**Comment by HadiNiazi** [comment]
@sayedahmadnawid Yes it's the appending event on the front end side but not saving them on the back end side that's the event is disappearing. 
Also, this is your code problem, not the repo issue, so be relevant to create the issue.

**Comment by sayedahmadnawid** [comment]
@HadiNiazi Thank you for the prompt response. 

I am sorry for the confusion. In fact, the very moment any task is created, it is saved in the backend. No problem with that part. However, whenever the calendar page is visited, the tasks are not being fetched but if I navigate on the calendar by pressing any button going back and forth the tasks are being fetched and appear properly. 

**Note:** Actually, it is the full-calendar issue, not your code, I went through several forums, and still people are struggling with it. 

Anyhow, thank you.

**Comment by sayedahmadnawid** [comment]
By the way, I found my answer here. 

https://github.com/HadiNiazi/fullCalendar-js-in-Laravel/issues/2

Thank you

**Comment by sayedahmadnawid** [comment]
For each task, there are 3 extra characters "12a" appears as a prefix. 

I appended the following snippet in three places: create, destroy, and replaced your CSS with it. I am sure it is not good practice but at least it removes those unnecessary letters.

 $('.fc-event').each(function () {
                var str = $(this).text();
                $(this).text(str.substring(3));
            })
